server {
    listen 8080;
    root /webserv/configs/client_max_body_size/www;
    client_max_body_size 100k;

    location / {
        root /webserv/configs/client_max_body_size/www;
        index index.html;
        allow_methods GET;
    }

    location /upload {
        root /webserv/configs/client_max_body_size/www;
        allow_methods POST;
        upload_store /webserv/configs/client_max_body_size/uploads;
    }
}
