server {
    listen 8080;
    root /webserv/configs/multi/site1;

    location / {
        root /webserv/configs/multi/site1;
        index index.html;
        allow_methods GET;
    }
}

server {
    listen 8081;
    root /webserv/configs/multi/site2;

    location / {
        root /webserv/configs/multi/site2;
        index index.html;
        allow_methods GET;
    }
}
