server {
    listen 8080;
    root /webserv/configs/allow_methods/www;

    location / {
        root /webserv/configs/allow_methods/www;
        index index.html;
        allow_methods GET;
    }

    location /upload {
        root /webserv/configs/allow_methods/www;
        allow_methods POST;
        upload_store /webserv/configs/allow_methods/uploads;
    }
}
