server {
    listen 8080;
    root /webserv/configs/full/www;
    client_max_body_size 10m;
    error_page 404 /404.html;

    location / {
        root /webserv/configs/full/www;
        index index.html;
        allow_methods GET;
    }

    location /files {
        root /webserv/configs/full/www;
        autoindex on;
        allow_methods GET DELETE;
    }

    location /old {
        return 301 http://localhost:8080/;
    }
}
