server {
    listen 8080;
    root /webserv/configs/errors/www;

    location / {
        root /webserv/configs/errors/www;
        index index.html;
        allow_methods GET;
    }

    location /post-no-store {
        root /webserv/configs/errors/www;
        allow_methods POST;
    }

    location /noindex {
        root /webserv/configs/errors/www;
        autoindex off;
        allow_methods GET;
    }
}
