server {
    listen 8080;
    root /webserv/www;
    client_max_body_size 1m;

    location /cgi-bin {
        root /webserv/www;
        allow_methods GET POST;
        cgi_ext .py /usr/bin/python3;
        cgi_ext .php /usr/bin/php-cgi;
    }
}
