server {
    listen 8080;
    root /webserv/configs/return/www;

    location / {
        root /webserv/configs/return/www;
        index index.html;
        allow_methods GET;
    }

    location /old {
        return 301 http://localhost:8080/new/;
    }

    location /new {
        root /webserv/configs/return/www;
        index index.html;
        allow_methods GET;
    }
}
