server {
    listen 127.0.0.1:8080;
    root /webserv/configs/multi_host/www;

    location / {
        root /webserv/configs/multi_host/www;
        index index.html;
        allow_methods GET;
    }
}

server {
    listen 0.0.0.0:8081;
    root /webserv/configs/multi_host/www;

    location / {
        root /webserv/configs/multi_host/www;
        index index.html;
        allow_methods GET;
    }
}
