server {
    listen 8080;
    root /webserv/configs/nested_locations/www;

    location / {
        root /webserv/configs/nested_locations/www;
        index index.html;
        allow_methods GET;
    }

    location /images {
        root /webserv/configs/nested_locations/www;
        autoindex on;
        allow_methods GET;
    }
}
