server {
    listen 9090;
    root /home/codeex/webserv/www/html;

    # Custom error pages (path relative to root)
    error_page 400 /errors/400.html;
    error_page 403 /errors/403.html;
    error_page 404 /errors/404.html;
    error_page 405 /errors/405.html;
    error_page 500 /errors/500.html;
    error_page 504 /errors/504.html;

    # Static website
    location / {
        root /home/codeex/webserv/www/html;
        index index.html;
    }

    # CGI scripts
    location /cgi-bin {
        root /home/codeex/webserv/www;
        cgi .py /usr/bin/python3;
        cgi .sh /bin/sh;
    }
}
