server {
    listen 8080;
    root /var/www/html;

    location / {
        root /var/www/html;
        index index.html;
        allow_methods GET;
    }

    location /upload {
        root /var/www/html;
        allow_methods POST DELETE;
    }
}
