server {
    listen 8080;
    root /webserv/www;
    client_max_body_size 10m;

    location / {
        root /webserv/www;
        index index.html;
        allow_methods GET;
    }

    location /upload {
        root /webserv/www;
        allow_methods POST;
        upload_store /webserv/uploads/files;
    }

    location /files {
        root /webserv/uploads;
        autoindex on;
        allow_methods GET DELETE;
    }
}
