server {
    listen 8080;
    root /var/www/html;

    location /old {
        root /var/www/html;
        return 301 http://localhost:8080/new;
    }

    location /new {
        root /var/www/html;
        index index.html;
    }
}
