server {
    listen 8080;
    root /webserv/configs/tester;

    location / {
        allow_methods GET;
        index index.html;
    }

    location /post_body {
        allow_methods POST;
        client_max_body_size 100;
    }

    location /directory {
        allow_methods GET POST;
        root /webserv/configs/tester;
        index youpi.bad_extension;
        cgi_ext .bla /webserv/cgi_tester;
    }

    location /YoupiBanane {
        allow_methods GET POST;
        root /webserv/configs/tester;
        cgi_ext .bla /webserv/cgi_tester;
    }
}
